on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: uv sync
      - name: Lint with Ruff
        run: uv run ruff check
      - name: Format with Ruff
        run: uv run ruff format
      - name: Type check with mypy
        run: uv run mypy .
      - name: Test with pytest
        run: uv run pytest
      - name: Check documentation build
        run: uv run mkdocs build
      - name: Check with pre-commit
        run: uv run pre-commit run --all-files